---
kind: pipeline
type: docker
name: default

steps:
- name: compile
  image: docker.io/procsiab/texlive-it:latest-amd64
  commands:
  - make all

- name: deploy
  image: appleboy/drone-scp
  failure: ignore
  settings:
    host: 192.168.1.100
    username: astro
    key:
      from_secret: astro-drone-key
    port: 22
    target: /srv/book/
    source: pdf/ns-workbook.pdf
    strip_components: 1
  when:
    branch:
    - master
    status:
    - success

- name: debug
  image: docker.io/busybox:latest
  failure: ignore
  commands:
  - cat pdf/main.log
  when:
    branch:
    - master
    status:
    - failure

---
kind: signature
hmac: 4762ab6eab9dd596f79c33862db7269ce8850b0d3164cc0c607a219959efebbc

...
